version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: cognitive-retraining-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: cognitive-retraining
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - cognitive-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cognitive-retraining-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/cognitive-retraining?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - cognitive-network

  # EEG Processor
  eeg-processor:
    build:
      context: ./eeg-processor
      dockerfile: Dockerfile
    container_name: cognitive-retraining-eeg
    restart: unless-stopped
    environment:
      FLASK_ENV: development
      PORT: 5001
      BACKEND_URL: http://backend:5000
    ports:
      - "5001:5001"
    depends_on:
      - backend
    volumes:
      - ./eeg-processor:/app
    networks:
      - cognitive-network

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cognitive-retraining-frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:5000
      REACT_APP_EEG_URL: http://localhost:5001
      REACT_APP_SOCKET_URL: http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - eeg-processor
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - cognitive-network

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: cognitive-retraining-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
      - eeg-processor
    networks:
      - cognitive-network

  # Redis for caching and sessions (Optional)
  redis:
    image: redis:7-alpine
    container_name: cognitive-retraining-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cognitive-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  cognitive-network:
    driver: bridge